version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - MONGO_URI=${MONGO_URI}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HEROKU_APP_URL=${HEROKU_APP_URL}
